import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header/Header'
import { AppProvider } from '@/context/AppProvider'
import styles from '@/app/page.module.css'
import { Chips } from '@/components/Chips/Chips'
import { ThemeProvider } from '@mui/material'
import theme from '@/app/theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EvilUnion Test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <ThemeProvider theme={theme}>
            <Header />
            <main className={styles.main}>
              <Chips />
              {children}
            </main>
          </ThemeProvider>
        </AppProvider>
      </body>
    </html>
  )
}
